[project]
name = "techtonic"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aenum==3.1.15",
    "aiodns==3.2.0",
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.4.4",
    "aiohttp==3.11.9",
    "aiosignal==1.3.1",
    "annotated-types==0.7.0",
    "anyio==4.6.2.post1",
    "asgiref==3.8.1",
    "attrs==24.2.0",
    "autobahn==24.4.2",
    "automat==24.8.1",
    "blinker==1.8.2",
    "brotli==1.1.0",
    "cachetools==5.5.0",
    "certifi==2024.8.30",
    "cffi==1.17.1",
    "channels==4.2.0",
    "channels-redis==4.2.1",
    "charset-normalizer==3.4.0",
    "clerk-backend-api==1.7.0",
    "click==8.1.7",
    "constantly==23.10.4",
    "cryptography==43.0.3",
    "daphne==4.1.2",
    "dataclasses-json==0.6.7",
    "deepgram-sdk==3.10.0",
    "defusedxml==0.8.0rc2",
    "deprecated==1.2.17",
    "deprecation==2.1.0",
    "distro==1.9.0",
    "dj-database-url==2.1.0",
    "django==5.1.3",
    "django-environ==0.12.0",
    "django-extensions==3.2.3",
    "djangorestframework==3.15.2",
    "eval-type-backport==0.2.2",
    "flask==3.0.3",
    "frozenlist==1.5.0",
    "google-api-core==2.23.0",
    "google-auth==2.36.0",
    "google-cloud-texttospeech==2.21.1",
    "googleapis-common-protos==1.66.0",
    "groq==0.18.0",
    "grpcio==1.68.1",
    "grpcio-status==1.68.1",
    "gtts==2.5.4",
    "gunicorn==22.0.0",
    "h11==0.14.0",
    "httpcore==1.0.6",
    "httpx==0.28.1",
    "hyperlink==21.0.0",
    "idna==3.10",
    "incremental==24.7.2",
    "itsdangerous==2.2.0",
    "jinja2==3.1.4",
    "jiter==0.7.0",
    "jsonpath-python==1.0.6",
    "markupsafe==3.0.2",
    "marshmallow==3.23.1",
    "msgpack==1.1.0",
    "multidict==6.1.0",
    "mypy-extensions==1.0.0",
    "oauthlib==3.2.2",
    "openai==1.61.1",
    "packaging==24.2",
    "propcache==0.2.1",
    "proto-plus==1.25.0",
    "protobuf==5.29.1",
    "psycopg2-binary==2.9.9",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.1",
    "pycares==4.5.0",
    "pycparser==2.22",
    "pydantic==2.10.6",
    "pydantic-core==2.27.2",
    "pyjwt==2.10.1",
    "pyopenssl==25.0.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "python3-openid==3.2.0",
    "pytz==2024.2",
    "redis==5.2.1",
    "requests==2.32.3",
    "requests-oauthlib==2.0.0",
    "rsa==4.9",
    "service-identity==24.2.0",
    "setuptools==75.8.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "social-auth-app-django==5.4.2",
    "social-auth-core==4.5.4",
    "sqlparse==0.5.2",
    "svix==1.56.0",
    "tqdm==4.66.6",
    "twisted==24.11.0",
    "txaio==23.1.1",
    "types-deprecated==1.2.15.20241117",
    "types-python-dateutil==2.9.0.20241206",
    "typing-extensions==4.12.2",
    "typing-inspect==0.9.0",
    "urllib3==2.2.3",
    "websockets==13.1",
    "werkzeug==3.1.1",
    "whitenoise==6.9.0",
    "wrapt==1.17.2",
    "yarl==1.18.3",
    "zope-interface==7.2",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]
