# Generated by Django 5.1.3 on 2024-12-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical')], default='technical', max_length=20),
        ),
    ]
