# Generated by Django 5.1.3 on 2024-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_assessment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='score',
        ),
        migrations.AddField(
            model_name='assessment',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
